### ISSUE TITLE
Fastcgipp::Socket Fastcgipp::SocketGroup::poll(bool) ERROR

### ISSUE THREAD

**Issue by ZhangzheBJUT** [eddic/fastcgipp#27]
/src/sockets.cpp:523:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if(events == pollIn)
                           ^
/src/sockets.cpp:538:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if(events == pollIn)

compile with gcc5.2 
how to deal with ti ?

**Comment by luoxing91** [comment]
i meet a same problem ,

**Comment by Erroneous1** [comment]
This doesn't happen on Linux with GCC 8.1.0 or Clang 6.0.0. What are the types for events and pollIn on your systems?
